[package]
name = "parse-markdown"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
dioxus-rsx = "0.6.0-alpha.5"
proc-macro2 = { version = "1.0", features = ["span-locations"] }
pulldown-cmark = "0.9.3"
quote = "1.0.37"
regex = "1.11.1"
syn = "2.0.89"
syntect = "5.2.0"
